---
- name: Run contentmirror.raw role
  hosts: all
  connection: local
  gather_facts: true
  tasks:
    - name: Run raw role
      ansible.builtin.include_role:
        name: raw
      vars:
        raw_src: '{{ src }}'
        raw_dst: '{{ dst }}'
        raw_dst_auth_user: '{{ dst_auth_user | default(omit) }}'
        raw_dst_auth_password: '{{ dst_auth_password | default(omit) }}'
