---
- name: Run contentmirror.raw role
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: 'Include raw'
      ansible.builtin.include_role:
        name: raw
      vars:
        raw_src: '{{ raw_file.src }}'
        raw_dst: '{{ raw_file.dst }}'
      loop: '{{ download_raw_files }}'
      loop_control:
        loop_var: raw_file
