---
- name: Run contentmirror.raw
  hosts: raw
  connection: local
  gather_facts: false
  tags:
    - raw
  tasks:
    - name: Run raw role
      ansible.builtin.include_role:
        name: raw
      vars:
        raw_src: '{{ src }}'
        raw_dst: '{{ dst }}'
        raw_dst_auth_user: '{{ dst_auth_user | default(omit) }}'
        raw_dst_auth_password: '{{ dst_auth_password | default(omit) }}'

- name: Run contentmirror.oci
  hosts: oci
  connection: local
  gather_facts: false
  tags:
    - oci
  tasks:
    - name: Run oci role
      ansible.builtin.include_role:
        name: oci
      vars:
        oci_src: '{{ src }}'
        oci_dst: '{{ dst }}'
        oci_dst_auth_user: '{{ dst_auth_user | default(omit) }}'
        oci_dst_auth_password: '{{ dst_auth_password | default(omit) }}'
